version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vape-frontend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - vape-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`podzoon.com`) || Host(`www.podzoon.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

networks:
  vape-network:
    external: true
